apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: fenix23707/restaurant
          imagePullPolicy: Always
          ports:
            - containerPort: 2001

---

apiVersion: v1
kind: Service
metadata:
  name: restaurant
  labels:
    app: restaurant
spec:
  type: LoadBalancer
  ports:
    - port: 2001
  selector:
    app: restaurant
